version: '3'

services:
  mongoDB:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongoDB:/data/db 

  contact3210-backend-image:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongoDB:27017
      DB_NAME: ProductDB
      NAME: TrulyMittal
    depends_on:
     - mongoDB

volumes:
  mongoDB: {}
